### ISSUE TITLE
Support keycap labels for each keyboard language setting

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#175]
There are an option to change mainly symbols sent by pressing a Shift key which can set by OS. For example, when the "US Keyboard" is set and pressing the "Shift + 2", the "@" symbol is sent. In the other hand, if the "JIS Keyboard" is set and pressing the "Shift + 2", the double quotation symbol is sent.

We guess that Remap users can recognize more easily what is the "2" key if the keycap is shown as "2 and @".

**Comment by yoichiro** [comment]
@adamrocker I created the language definition file. It was created automatically by using my script, and the script read the keymap-[lang].h files in the QMK Firmware.

[languages.json.zip](https://github.com/remap-keys/remap/files/6020204/languages.json.zip)

**Comment by yoichiro** [comment]
@adamrocker I would like to send you the updated `languages.json` file. In this file, each modifier represents as an array like `"modifiers":["RightShift", "RightCtrl"]`.

[languages.zip](https://github.com/remap-keys/remap/files/6039679/languages.zip)

**Comment by adamrocker** [comment]
@yoichiro Thanks! I'm gonna implement them into our app ;)
