### ISSUE TITLE
Support a Rotary Encoder control

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#201]
The current VIA supports a rotary encoder control for some keyboards.

See: https://docs.cannonkeys.com/satisfaction75/user_guide/#via-support

**Comment by BenRoe** [comment]
Here is the example how VIAL handles it. 
https://get.vial.today/gettingStarted/encoders.html

**Comment by yoichiro** [comment]
@BenRoe Thank you for posting the information! I read and will understand it absolutely.

**Comment by yoichiro** [comment]
Since the VIA protocol version 0x0A, the VIA protocol provides two new commands: Get dynamic keymap encoder and Set dynamic keymap encoder. We intend to support Encoders in Remap with their commands.

**Comment by yoichiro** [comment]
This was supported at #739. I close this issue.
