### ISSUE TITLE
Page transition to the keyboard list when user added a new keyboard permission from header

### ISSUE THREAD

**Issue by adamrocker** [remap-keys/remap#205]
Need to reset inner states so we should make the page transition to the keyboard list.
<img width="456" alt="スクリーンショット 2021-01-20 18 32 53" src="https://user-images.githubusercontent.com/316463/105155653-359d2580-5b4e-11eb-9958-d7c71af1c763.png">

**Comment by yoichiro** [comment]
When I tested this behavior, I could confirm that the behavior has already been what we expected. I close this.
