### ISSUE TITLE
Keep the setting of the layout option.

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#221]
As title. Probably, we may store the setting values into the local storage of the Chrome browser.

**Comment by adamrocker** [comment]
[memo for me]
need to check the saved settings are available to the current keyboard definition.

**Comment by tmor** [comment]
First of all, thank you for useful service.

I'm using a keyboard with JIS layout.
Currently, every time I open Remap, it reverts to US layout.
I want to save the JIS layout.

My env:
- keyborad: jisplit89
- OS: Win 10 Pro 2004
- Vivaldi: 3.7.2218.45 (Stable channel) (64-bit)

![remap-2021-03-25](https://user-images.githubusercontent.com/1677832/112446977-20ce4f80-8d94-11eb-99e7-2a4b40f7feb6.jpg)

**Comment by yoichiro** [comment]
@tmor This issue covers layout options for keys, does not cover the language option. I will create another issue for the language selection.
