### ISSUE TITLE
 hotdox layout not apearing complete

### ISSUE THREAD

**Issue by IsmaelAlvarez** [remap-keys/remap#303]
![image](https://user-images.githubusercontent.com/7153162/108285895-e0612d80-7166-11eb-9809-dc7deff14807.png)

on each side there are keys not apearing, they are the second last keys ond thumb cluster, im adding via picture for reference

![image](https://user-images.githubusercontent.com/7153162/108286025-1c948e00-7167-11eb-885d-0e0a9599dc70.png)

this definitions used 

https://github.com/the-via/keyboards/tree/master/src/hotdox

**Comment by yoichiro** [comment]
Probably, [this JSON file](https://github.com/the-via/keyboards/blob/703e53b6f9d89cf0f3667da2a65afd06e1b2376f/src/hotdox/hotdox.json) is applied. I thought that there are one or more layout option, but nothing...

@adamrocker Could you confirm this issue?

**Comment by adamrocker** [comment]
Sure. I assigned this issue to me ;)

**Comment by adamrocker** [comment]
@IsmaelAlvarez Thank you for your report. I checked key rendering algo and fixed it.
Fixed version of Remap will be deploy soon.
Please reload Remap web app and make sure it works.
