### ISSUE TITLE
2U Vertical Keys Split issue

### ISSUE THREAD

**Issue by Xelus22** [remap-keys/remap#354]
Hi Remap team,

I have an issue with my AEBoards EXT65. The vertical 2U key is misaligned when split into 2x 1U keys.

![image](https://user-images.githubusercontent.com/17491233/109740275-ede4d180-7bc2-11eb-8b75-a763ba155f94.png)
![image](https://user-images.githubusercontent.com/17491233/109740305-f9d09380-7bc2-11eb-8e0c-41a199578971.png)
![image](https://user-images.githubusercontent.com/17491233/109740344-09e87300-7bc3-11eb-8954-4bac7ccedb67.png)

**Comment by adamrocker** [comment]
@Xelus22 Thank you for your report! Is there this keyboard definition file I can access?

**Comment by Xelus22** [comment]
Yep the file is here:
https://github.com/the-via/keyboards/blob/master/src/aeboards/ext65/aeboards_ext65.json
Thanks

**Comment by adamrocker** [comment]
Thank you for sharing the file. I can understand the situation. I'm gonna fix it :)

**Comment by adamrocker** [comment]
@Xelus22 I fixed this bug. Could you please check the behavior with your environment?

**Comment by Xelus22** [comment]
Yep works perfectly now thank you!
![image](https://user-images.githubusercontent.com/17491233/109910344-cf083d00-7c9f-11eb-8c56-3d28162f9d5e.png)
