### ISSUE TITLE
[Feature Request] RGBLIGHT mode changer

### ISSUE THREAD

**Issue by Xelus22** [remap-keys/remap#356]
Currently VIA allows support of changing RGBLIGHT as a GUI.

Hopefully remap can do this as well in future. :D

![image](https://user-images.githubusercontent.com/17491233/109753864-df0a1900-7bda-11eb-86b0-2273ec7ab6bc.png)
![image](https://user-images.githubusercontent.com/17491233/109753874-e3cecd00-7bda-11eb-93e9-f2b4ad3e0105.png)

**Comment by yoichiro** [comment]
@Xelus22 The lighting feature has already been provided on Remap. If you click the gear icon,

![Screenshot from 2021-03-03 16-54-20](https://user-images.githubusercontent.com/261787/109772565-7b670680-7c41-11eb-9e8b-608298ae4898.png)

you can see the control dialog to set each lighting configuration. Could you confirm this feature on your environment and your keyboard?

![Screenshot from 2021-03-03 16-54-32](https://user-images.githubusercontent.com/261787/109772684-a05b7980-7c41-11eb-87cb-8f0dc23cd98c.png)

**Comment by Xelus22** [comment]
Oh, my keyboard doesnt have RGB effects. Sorry about that. Didn't know it was already implemented.
Would it be better to have another tab instead of in the "settings" ?

**Comment by yoichiro** [comment]
> Would it be better to have another tab instead of in the "settings" ?

@Xelus22 Yeah, we may need to improve the UI.

@adamrocker Let's discuss this issue as well during the UI improvement including removing the menu.

**Comment by yoichiro** [comment]
@Xelus22 I close this issue. We intend to continue the discussion about the UI improvement on #357. Thanks!
