### ISSUE TITLE
Improve the UI (mainly the menu)

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#357]
Currently, there is a menu UI component on the top of the right. The menu has one menu item to export a cheat sheet.

<img width="1069" alt="スクリーンショット 2021-03-04 6 13 23" src="https://user-images.githubusercontent.com/261787/109873222-cff59a80-7cb0-11eb-8c94-624e8773d072.png">

If we add a new menu to provide some menu items about user's preferences at the right on the header after releasing a login feature, two menus will be put on very near place. This is not good.

Also, if we put icons to invoke each function as like a general toolbar (that is, not use the menu component), users will be able to invoke them more easily than now.

**Comment by yoichiro** [comment]
@adamrocker In the discussion #356, the issues reporter could not notice the existence of the lighting configuration feature. Well, I guess that we should put an icon to open the lighting feature dialog on the icons bar discussing on this issue.

**Comment by adamrocker** [comment]
@yoichiro Good idea! I agree with you.

**Comment by adamrocker** [comment]
I've just added the issue which puts the lighting menu on the feature menu.
https://github.com/remap-keys/remap/issues/359
