### ISSUE TITLE
Formatting and markup broken

### ISSUE THREAD

**Issue by ruddy17** [remap-keys/remap#371]
I installed a fresh Chrome to test our remap with my macropad. I noticed a couple glitches:
1. The tabs of keycode palette are hidden and unlabeled
2. Some labels on the device view overlap each other, some don't fit inside the keycap frame.
![изображение](https://user-images.githubusercontent.com/4340532/110095340-dfa6d900-7dad-11eb-9a7a-f891e82c8b12.png)

**Comment by adamrocker** [comment]
@ruddy17 Thanks for your report :) I'll make the reproduction environment and fix it.

**Comment by adamrocker** [comment]
@ruddy17 I fixed this bug. The app will be deployed soon. Please check it :)
