### ISSUE TITLE
Cannot replace KeyboardDefinition json with local file

### ISSUE THREAD

**Issue by elfmimi** [remap-keys/remap#376]
Apply button seems to stop working somewhere between 619bb7f and b7e8394. probably at https://github.com/remap-keys/remap/commit/8c33f39aa78a68fd19e17c5532d5ea55fbe1a8f1

With the former ConfigurationDialog , I could successfully upload json file for a keyboard already registered in remap's database. 
It seems I cannot do the same with ImportDefDialog .

**Comment by adamrocker** [comment]
I confirmed the bug. I'm gonna fix it ASAP!

**Comment by adamrocker** [comment]
@elfmimi Thank you for your report. I fixed the bug. The new build will be deployed in a few minutes. Please check it.
