### ISSUE TITLE
Assign EEPROM_RESET in QMK Keycodes with Remap

### ISSUE THREAD

**Issue by e3w2q** [remap-keys/remap#381]
When I overwrite the firmware, the keymap sometimes goes wrong in my environment.
Also, with dynamic keymaps, even if I overwrite the firmware, the keymap before the overwrite is retained and not reset.
I think it would be useful to assign EEPROM_RESET in QMK Keycodes with Remap.
https://docs.qmk.fm/#/quantum_keycodes

**Comment by adamrocker** [comment]
@e3w2q Thank you for your report. I added it to the DEVICE category as below:
<img width="1674" alt="スクリーンショット 2021-03-10 6 15 58" src="https://user-images.githubusercontent.com/316463/110540038-56a2ef80-8169-11eb-861c-7b72dd8539f9.png">


Please check it. Enjoy :)
