### ISSUE TITLE
1st scope of this Remap product

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#40]
We define the 1st scope (this means a function set provided by the first version of this product) of this product as the following:
このプロダクトの最初のバージョンにて提供される初期スコープについて、以下のように定義します:

## 含まれる機能 

* 接続されたキーボードのWebHIDを使ったキーマップ操作（認可、表示、更新）。
* キーボード定義JSONファイルのアップロードとそれを使ったキーマップの編集。
* 登録済みキーボードが接続された際の自動認識とキーマップ編集開始。
* 定義済みキーコードの割り当てと、任意のキーコード（ANY）の割り当て。

## 含まれない機能

* キーボード定義JSONファイルの登録フォーム。
* 接続されていないキーボードのキーマップ編集。
* キーマップ定義情報のバックアップおよびリストア。
* OSの設定に依存するキーボード種別（US、日本語、PC98互換、など）に応じた記号などの表示。
* UI の i18n 対応（最初は英語のみ）。
* キーバインディング（Ctrl + Alt + A など）の表示。
* キーマップ定義情報のシェア。
* LEDの制御。
* マクロの登録。

**Comment by yoichiro** [comment]
@adamrocker 考えてみました。いかがでしょうか？

**Comment by adamrocker** [comment]
@yoichiro okでっす！

**Comment by yoichiro** [comment]
@adamrocker マクロの登録については初期リリースから外しても良いかなと思っています。ちょっとHid側でまだ試せていないためです。
