### ISSUE TITLE
Large Layout with small screen

### ISSUE THREAD

**Issue by AndyChiu** [remap-keys/remap#400]
Hi, I found a problem, when my keyboard is too large, and screen too small, the web page cannot accommodate the layout, the web page screen cannot be dragged like the KLE web side. The tool buttons can only be displayed when the web  page is reduced to 50%. However, the screen cannot be seen clearly when use 50%. Is there a way to improve this problem?  Thank you!

![rep01](https://user-images.githubusercontent.com/1038943/111111904-cbd54280-8524-11eb-9dc4-bc37b64256fd.png)
can't move screen to see all layout and choice tool button

![rep03](https://user-images.githubusercontent.com/1038943/111111898-ca0b7f00-8524-11eb-9334-64ceba5e04a9.png)
resize web page is ok but can't seen clearly

![rep02](https://user-images.githubusercontent.com/1038943/111111907-cd9f0600-8524-11eb-9bab-dc69e76ce0d5.png)
KLE can move and see all layout and function button

**Comment by yoichiro** [comment]
@AndyChiu To reproduce this issue, could you share us the JSON file and the hex file?

**Comment by AndyChiu** [comment]
Yes! Tks!
[Universal-Century(willow64+extension-to-108)-REMAP.zip](https://github.com/remap-keys/remap/files/6139231/Universal-Century.willow64%2Bextension-to-108.-REMAP.zip)

[UC_default.zip](https://github.com/remap-keys/remap/files/6139246/UC_default.zip)

**Comment by AndyChiu** [comment]
the screen size is 1024*768

**Comment by yoichiro** [comment]
@AndyChiu Thank you for the sharing.

**Comment by adamrocker** [comment]
@AndyChiu Hi Andy,
Thank you for using Remap and report the bug. I fixed it :) Please check it on build:43. Thanks.

**Comment by AndyChiu** [comment]
Hi, now i try build:44
the have vertical scoll bar, but don't have horizontal scroll bar, i can use arrow key to control horizontal scroll, but if have horizontal scroll bar is better!

![rep0317](https://user-images.githubusercontent.com/1038943/111430342-db3cc300-86bf-11eb-9c41-44d387798982.png)

**Comment by yoichiro** [comment]
@adamrocker Hmm... Could you confirm whether this issue was fixed or not in the latest revision?

**Comment by adamrocker** [comment]
@AndyChiu Thank you for checking that. At this moment, please use left/right arrow key to scroll right and left.
I can move for side direction using mouse scroll and those keys.

I'm considering to fix to show the side scroll bar.
Sorry for the inconvenience this may have caused.

**Comment by adamrocker** [comment]
@AndyChiu Again, I fixed it. Please check it when you have available time :)

**Comment by AndyChiu** [comment]
@adamrocker Thank you! so fast so nice!  👍
