### ISSUE TITLE
7skb keyboard layout is not drawn correctly

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#448]
![Screenshot_20210428_092305](https://user-images.githubusercontent.com/261787/116328506-217b5b00-a804-11eb-8e64-0c396b771c88.png)

When selecting the `Choc` layout option, some keys were not drawn correctly.

**Comment by yoichiro** [comment]
@adamrocker Could you confirm this issue? Thanks.

**Comment by yoichiro** [comment]
I captured the window of VIA, when I tested this behavior on VIA client app.

![Screenshot_20210428_093150](https://user-images.githubusercontent.com/261787/116328787-bbdb9e80-a804-11eb-9ab6-19d5e6a36dd0.png)

![Screenshot_20210428_093207](https://user-images.githubusercontent.com/261787/116328795-bed68f00-a804-11eb-9560-bc919244dcc9.png)

**Comment by adamrocker** [comment]
I investigated the JSON and found that it has the wrong format.
The "9,0" key does not have an "Option Choice" label, on the other hand, the VIA's JSON has it.
The size of choice keys: "4,4", "9,0", are also wrong.

The layout of uploaded JSON is as below:
<img width="893" alt="スクリーンショット 2021-04-29 5 51 29" src="https://user-images.githubusercontent.com/316463/116472715-3c57d900-a8b1-11eb-8a5c-a4318b4baf25.png">

The VIA's JSON is as below:
<img width="889" alt="スクリーンショット 2021-04-29 5 52 29" src="https://user-images.githubusercontent.com/316463/116472797-55608a00-a8b1-11eb-941f-605b3232a2a4.png">

**Comment by yoichiro** [comment]
I close this issue because this issue caused by the specific keyboard definition.
