### ISSUE TITLE
"MUST have .json extention" error though it's json

### ISSUE THREAD

**Issue by miyamonz** [remap-keys/remap#449]
## What happened

I'm using moonlander, which isn't supported by Remap.
so I prepared its JSON file.
but it failed.
[![Image from Gyazo](https://i.gyazo.com/bd4213fbe65b8d06ddc1be5120959b06.png)](https://gyazo.com/bd4213fbe65b8d06ddc1be5120959b06)

## why
I surveyed this and found the reason.
the File.type is not `application/json` but `text/plain` on my environment. Windows 10, chrome.

this is a very small reproduction.
https://codesandbox.io/s/dank-fog-k6w6v
I tested on this.
when it's windows, it's text/plain
when it's Mac, it's application/json with a same json file.

I don't check the detail, but probably the File.type isn't correct.

ref: https://developer.mozilla.org/en-US/docs/Web/API/File/type

## suggestion
I don't know why such a difference happens, and understand it's not Remap's bug.
anyway, modifying the below will fix this problem.

https://github.com/remap-keys/remap/blob/693c38c2883991b974f10c1e32d9f2cde4deca75/src/services/storage/Validator.ts#L25-L27

like this:
```js
function isJSON(sJSON){
    try {
        JSON.parse(sJSON);
        return true;
    } catch (e) {
        return false;
    }
}
```

if it's OK, I will send pull req.

**Comment by yoichiro** [comment]
@miyamonz Thank you for this report and the investigation. I agree the modification you suggested. Could you create a pull request?

**Comment by yoichiro** [comment]
@miyamonz I have just merged the pull request #452. Could you test the latest behavior?

**Comment by yoichiro** [comment]
I close this issue.

**Comment by miyamonz** [comment]
yes! it works. thank you!
