### ISSUE TITLE
Attack25 rev3 layout broken

### ISSUE THREAD

**Issue by monksoffunk** [remap-keys/remap#455]
![image](https://user-images.githubusercontent.com/16618674/120415205-1d5bd380-c396-11eb-9d00-68e784f3e6b5.png)
Layout broken when layout option 'Encoder' is off.

https://discord.com/channels/802306358938435605/808957769415786536/849473200995696661

**Comment by yoichiro** [comment]
@adamrocker It seems that there is something issue about rendering the key layout with a layout option. Could you investigate and try to fix this issue?

**Comment by yoichiro** [comment]
@monksoffunk We're investigating this issue. But, we guess that it will take a long time a bit to fix this issue completely. As the alternate way, this issue does not occur when the rotary encoder is shown as default. If you want to avoid this issue soon, could you modify the JSON file to change the default behavior to show the rotary encoders?
