### ISSUE TITLE
[Documentation] json file format documentation is not easy to locate

### ISSUE THREAD

**Issue by jaygreco** [remap-keys/remap#460]
We're exploring adding remap support for our nullbits products as a VIA alternative. There is currently no documentation that is easily discoverable (<5min) that details the process of adding a new keyboard or porting from a VIA json file. This documentation will help encourage adoption.

**Comment by yoichiro** [comment]
@jaygreco Sorry for this late reply. Basically, you can send a review request from the following URL with the VIA JSON file without any modification: https://remap-keys.app/keyboards But I intend to write a document to describe how to register a keyboard to Remap soon. Please give me a few days.

**Comment by jaygreco** [comment]
Not a problem at all! I was able to find the spec and add a keyboard. This would still be helpful for those who are looking to port support from VIA. 

Thanks for the response!

**Comment by jaygreco** [comment]
Not a problem at all! I was able to find the spec and add a keyboard. This would still be helpful for those who are looking to port support from VIA. 

Thanks for the response!
