### ISSUE TITLE
[Layout] keymap crooked 

### ISSUE THREAD

**Issue by 3araht** [remap-keys/remap#494]
As shown below, the 'floating' keys are misaligned, and the other keymaps are also shown incorrectly.
It affects the other layers.

This is the keymap how it should be, drawn by [Keyboard Layout Editor](http://www.keyboard-layout-editor.com/).
<img width="1199" alt="Screen Shot 2021-07-11 at 17 08 24" src="https://user-images.githubusercontent.com/69518343/125194937-6274fe80-e28e-11eb-8a2d-687a365eb2a2.png">

And this is how it was shown in REMAP.
<img width="1299" alt="Screen Shot 2021-07-11 at 17 11 12" src="https://user-images.githubusercontent.com/69518343/125195001-a7993080-e28e-11eb-8a79-3f2062e56908.png">

The "Layout Option" doesn't work.

Other layers are affected, as well. Here's the code, 
<img width="1252" alt="Screen Shot 2021-07-11 at 21 33 53" src="https://user-images.githubusercontent.com/69518343/125195248-d1068c00-e28f-11eb-8fb8-8cc7a0bcfc37.png">

And here's the cheat sheet.
[keymap_cheatsheet_chromatonemini.pdf](https://github.com/remap-keys/remap/files/6796902/keymap_cheatsheet_chromatonemini.pdf)

**Comment by 3araht** [comment]
[Here's](https://github.com/3araht/chromatonemini/blob/main/temp/qmk_firmware/keyboards/chromatonemini/chromatonemini_via.json) the json file.

**Comment by yoichiro** [comment]
@3araht Thank you for the report! Could you also submit your hex file? We will be able to reproduce this issue more easily on our local environment.

**Comment by 3araht** [comment]
Here you are.
https://github.com/3araht/chromatonemini/blob/main/chromatonemini_via_hex.zip

**Comment by yoichiro** [comment]
@3araht Thank you for the submitting the hex file! We will investigate this issue and will send feedback after that.

**Comment by yoichiro** [comment]
@adamrocker Could you investigate this issue?

**Comment by adamrocker** [comment]
I've investigated this issue and found a problem with the definition of the key's matrix in the JSON.

**Comment by yoichiro** [comment]
@adamrocker Thank you for the investigating!

@3araht I think that you have already updated the keyboard definition JSON file to fix this issue. I close this issue, but you can reopen this issue anytime, when you find other issues regarding this.. Thank you for your contribution!
