### ISSUE TITLE
Web page typo

### ISSUE THREAD

**Issue by jpskenn** [remap-keys/remap#498]
"Text Matrix" --> "Test Matrix".
<img width="506" alt="スクリーンショット 2021-07-14 4 50 35" src="https://user-images.githubusercontent.com/22065528/125525316-4703824f-a74c-42d1-bd42-8133c2d94576.png">

**Comment by yoichiro** [comment]
@jpskenn I have fixed this issue and the new revision has already been released. Thank you for the reporting!
