### ISSUE TITLE
Lang5 is sent when tapping JIS Zenkaku/Hankaku

### ISSUE THREAD

**Issue by soogie** [remap-keys/remap#548]
Hold/TapのTap欄の候補には「半角/全角」が出てこず，選択できるのはJIS Zenkaku/Hankakuです。

そこでこのように設定しました。
![image](https://user-images.githubusercontent.com/6476040/128626617-108559b3-6a10-497b-8b77-1ff58e2f77f5.png)
![image](https://user-images.githubusercontent.com/6476040/128626664-29a60bda-afaf-45c1-871e-69d8fc0e423f.png)

しかしWindows機につないでこのキーをタップしても半角/全角キーとして機能しません。

あらためてMacに繋ぎ直してkaravinar event viewerで送出されるキーを確認したところ，lang5が送出されていました。
![image](https://user-images.githubusercontent.com/6476040/128626702-1f24f8bf-4364-4f96-aea7-19eade9df56e.png)

正しくはKC_GRVを送出し，こうなるはずだと思います。
![image](https://user-images.githubusercontent.com/6476040/128626835-1ef8fda5-285d-47c5-9037-f4407fdc1a94.png)

なお，単体で「半角/全角」をドラッグ＆ドロップした際は問題ありませんがKey欄でJIS Zenkaku/Hankakuを選択すると同様の挙動となります。

ご確認いただけますでしょうか。

**Comment by yoichiro** [comment]
@soogie Issue登録ありがとうございます。状況を確認いたしました。複数の要因が重なった結果、ご報告の状況となった模様です。

まず、`KC_LANG5` の Label として `JIS Zenkaku/Hankaku` と表示されていますが、これは QMK Firmware の [Full Keycode List](https://docs.qmk.fm/#/keycodes) に基づいて設定された結果です。ただし、これは実際には「半角/全角」キーを反映したものではないと考えられますので、修正の必要がありそうです（ `Language 5` に修正したほうが良さそうです）。

次に、ご指摘通り、`KC_GRAVE` のキーコード 0x35 が実際には「半角/全角」キーとなります。キーボードの言語を「Japanese」にした状態で、「KEY」タブで keycode に「半角」と入力すると、「半角/全角」が候補に出てきます。これは正しい動作かと思います。

<img width="473" alt="スクリーンショット 2021-08-08 19 26 45" src="https://user-images.githubusercontent.com/261787/128629111-a27ee87b-d34f-428e-a12a-7b9a36f46591.png">

しかし、「HOLD/TAP」タブにて「TAP」に「半角」と入力しても、確かに上記のように「半角/全角」が候補に出てきません。

<img width="479" alt="スクリーンショット 2021-08-08 19 26 59" src="https://user-images.githubusercontent.com/261787/128629136-d18a8d13-3265-471f-b207-e4d4eef001c1.png">

これは、おそらくキーボードの言語設定を変更した際に本来適用されるべき言語ごとのラベルが、HOLD/TAP タブ上にて考慮されていないのではないか、と推測されます。

@adamrocker 上記、確認できますでしょうか？

**Comment by yoichiro** [comment]
This issue occurs for Japanese keyboard only, therefore we're using Japanese to discuss about this issue.

**Comment by soogie** [comment]
Hold/Tapについては現象は解消しました。
![image](https://user-images.githubusercontent.com/6476040/128654031-cae396b2-eb54-4cf7-a616-7bc9eed13f2c.png)

単体キーについても何かアサインされている場合は問題なさそうです。
ただ，NOOPに割り当てたキーではKeycode欄の候補がおかしくなっています。
半角/全角が出てこないだけでなく，変換無変換やアルファベットのAすらも候補に出てきません。
![image](https://user-images.githubusercontent.com/6476040/128654127-2bfe18cf-4591-45b4-8a8e-66937e2362f9.png)

この状態でKeycode欄にAと入力してもこのようにアルファベットAが候補に出ません。
![image](https://user-images.githubusercontent.com/6476040/128654168-595b525c-6cbf-46b2-8030-fd398225f06f.png)

なお，ここからx(clear)をクリックして入力をキャンセルすると，全ての候補が正しく表示される状態になります。
![image](https://user-images.githubusercontent.com/6476040/128654220-8d2ba1bc-29db-400e-8057-cc30f70dba8e.png)

NOOP以外のキーの場合，最初にx(clear)をクリックするがNOOPでは最初から候補が出る，というところの違いが関係しているように思います。

**Comment by yoichiro** [comment]
@soogie ご報告いただいた挙動については「仕様通り」となります。NOOP（KC_NO） が割り当てられている状態では、KEY タブの Keycode フィールドには ` ` （空白一文字）が入力されています。その状態で補完候補一覧を表示した場合には「空白を含む候補の一覧」が表示されますので、例えば「A」については空白が含まれていませんので補完候補には出てきません。また、「半角/全角」についても空白が含まれませんので、同じく補完候補には含まれません。そして、NOOP を示す空白文字を削除する、もしくは X をクリックして同じく入力された文字を削除することで、全ての候補が表示されます。
