### ISSUE TITLE
[Feature Request] Download keymap file with QMK keycode

### ISSUE THREAD

**Issue by hsgw** [remap-keys/remap#550]
download a keymap file in a format that we can copy and paste into QMK Firmware's keymap.c.
for example,
```
  [KC_A, KC_B....], 
  [KC_1, KC_2....], 
```
This helps to compile the firmware and make the keymap persistent.
// Sorry, I made a mistake posting this without writing anything.

**Comment by yoichiro** [comment]
@hsgw Is what you expect a JSON file exported from a VIA app with "Save Current Layout"? Or, is that actual C code?

**Comment by hsgw** [comment]
I assumed it would be something similar to export from VIA.

**Comment by yoichiro** [comment]
@hsgw Could you describe some use cases about the feature you suggested?

**Comment by yoichiro** [comment]
@hsgw Thank you for the description. However, Remap is providing the Keymap Save/Restore feature to save multiple key mappings to the Remap database and to restore them. That is, users can persistent their key mappings by using the feature without downloading a file which has a key mapping.

What is the pros of your idea better than the save/restore feature?

**Comment by hsgw** [comment]
@yoichiro I think the save/restore function is not enough as far as the keymaps are only on EEPROM. As I mentioned in my previous post, EEPROM can be easily cleared.
Of course, the save/restore feature is useful, but it is inconvenient to use remap to restore keymap.

Also, it's useful for making the default keymap during development.

**Comment by adamrocker** [comment]
@hsgw Sorry, I'm confusing the situation you mentioned.
Let me clarify my understand.
 
Do you mean, you do NOT want to use Remap to restore the keymap you customized using Remap?

**Comment by hsgw** [comment]
> Do you mean, you do NOT want to use Remap to restore the keymap you customized using Remap?

Partially yes. I think it's too much trouble.
And, now I'm using VIA to export the keymap.

As a confirmation, there is no way to download the keymap locally in remap, right?

**Comment by adamrocker** [comment]
> As a confirmation, there is no way to download the keymap locally in remap, right?

Yes. Remap does not provide a download feature, now.

> Partially yes. I think it's too much trouble.
> And, now I'm using VIA to export the keymap.

Interesting! That's good news.
It's easy for you to customize a keymap using Remap. That's our goal, now.
And I could understand the background of your feature request is that it might be useful for keyboard designers/developers, like you, during keyboard designing/development.

Actually, the current save/restore keymap feature of Remap is for keyboard users, not keyboard designers/developers.
I think it's quite an interesting idea for expanding Remap features for designers/developers.

Anyway, I could understand that this request is for keyboard designers/developers.

@yoichiro 
We should keep considering the Remap roadmap not only for users but also for designers/developers, I think.
What do you say?

**Comment by yoichiro** [comment]
@adamrocker Yes, I agree your idea. We should consider a roadmap/features for keyboard designers/developers in the future, but unfortunatelly I think it is not now. We have still some plans to provide features for keyboard users. Also, we should design a feature set for keyboard designers/developers comprehensively. I guess that this proposal might be one of them or not.

**Comment by hsgw** [comment]
I understood about your roadmap. I hope it goes well👍
Thank you!

**Comment by gshmu** [comment]
I want update my keymap.c default keymap. 
That will make my tuning my keyboard smoother, instead of apply keymap after flash.  thank you

**Comment by mxmilkiib** [comment]
Could it be possible to reopen this issue as a placeholder for hopefully eventually exporing either the .c and .h/full firmware source, or a keymap JSON for QMK Configurator/VIA? Thanks!

If it's a QMK Configurator Keymap then the Configurator [etc.](https://jhelvy.shinyapps.io/qmkjsonconverter/) can export the source for playing about with in the terminal, so certain compex macros can be added (VIA can help with some macros but not all, and I'm not keen on the VIA interface).
