### ISSUE TITLE
Better layout or UI for when there are 10+ layers

### ISSUE THREAD

**Issue by elfmimi** [remap-keys/remap#553]
Currently it looks like this when the board has 31 layers.
![BLE-Micro-Pro-Remap-Keys](https://user-images.githubusercontent.com/2020873/129041405-f2dc7f2d-d08a-48e0-ad55-ab09307e612e.png)

**Comment by soogie** [comment]
@yoichiro  UIのレイヤー番号が0始まりだったのが1始まりになったため，UIで1番のレイヤーを選択すると0番のデフォルトレイヤーが表示されます。わかりにくいので0始まりに戻していただくことはできますか？

**Comment by yoichiro** [comment]
@soogie Yes, I will change the first layer number from 1 to 0.
