### ISSUE TITLE
[Feature request] Add an ANY key

### ISSUE THREAD

**Issue by shangsfanclub** [remap-keys/remap#580]
If there's an any key, that would allow people to add custom keycodes without relying only on the preset keys

**Comment by yoichiro** [comment]
You can set a custom key code on the `Custom` tab pane for each key.

![Screenshot_20210825_141814](https://user-images.githubusercontent.com/261787/130730891-4d2c0e85-685d-4e3d-9179-9c5ab01e923d.png)
