### ISSUE TITLE
Keyboard layout is not displayed (Browser gets whiteout)

### ISSUE THREAD

**Issue by jpskenn** [remap-keys/remap#589]
After connecting HID device, keyboard layout is not displayed(Browser gets whiteout).
This happens with "[Jones](https://remap-keys.app/catalog/z8HynboRCOQfPmwXbzp6)" keyboard.

For a moment, Header bar(Keyboard name, ID, etc.) and messages(*) displayed, then whiteout.

*messages:
- Fetching  keyboard definition.
- Opening keyboard.

Chrome DevTools Console log:
[remap-keys.app-1630106979687.log](https://github.com/remap-keys/remap/files/7069811/remap-keys.app-1630106979687.log)

**Comment by yoichiro** [comment]
@adamrocker We can reproduce this issue by accessing to the following URL: https://remap-keys.app/catalog/z8HynboRCOQfPmwXbzp6/keymap

When reproducing this issue, I got the following output in the console tab of the Chrome DevTools:

```
react-dom.production.min.js:216 TypeError: Cannot assign to read only property 'd' of object '#<Object>'
    at Function.assign (<anonymous>)
    at new e (KeyModel.ts:58)
    at KeyboardModel.ts:328
    at Array.forEach (<anonymous>)
    at e.value (KeyboardModel.ts:327)
    at new e (KeyboardModel.ts:164)
    at a.value (Catalogkeymap.tsx:101)
    at Ua (react-dom.production.min.js:187)
    at Fa (react-dom.production.min.js:186)
    at Vs (react-dom.production.min.js:269)
```

Probably, I guess that this issue was caused by the pull request #584. Could you confirm this issue?

**Comment by yoichiro** [comment]
@jpskenn Thank you for the reporting! We fixed this issue and now deploying the fixed version. Please confirm whether this issue has already been fixed or not.

**Comment by jpskenn** [comment]
Confirmed the issue fixed on "Build 125"👍
Thank you.
