### ISSUE TITLE
[Feature Request] Support QMK Bluetooth Keycodes

### ISSUE THREAD

**Issue by mrnoisytiger** [remap-keys/remap#596]
Hey there, I might be dense and missed this, but it seems like Remap doesn't have the keycodes for QMK bluetooth on there. Could those potentially be added into Device?

https://docs.qmk.fm/#/feature_bluetooth

**Comment by yoichiro** [comment]
@mrnoisytiger These key codes have been added into the device category. Thank you for the feedback!

![Screenshot_20210917_153405](https://user-images.githubusercontent.com/261787/133735785-d9e5b0c0-a3ea-4179-80b2-51cbb4c59431.png)
