### ISSUE TITLE
Invalid key layout is applied when importing JSON file which has same VID and PID and has different layout def from connected keyboard

### ISSUE THREAD

**Issue by soogie** [remap-keys/remap#603]
GherkinのVID 0xFEED，PID 0x6060は承認済みのCool836Aと重複しています。
そのため，Remapに接続した直後はCool836Aの36キーレイアウトが表示されます(これはOK)。

そこでImport keyboard definition fileでPiPi Gherkinのjsonをアップロード，反映すると，2レイヤー目の左上角のキー（数字の1）の位置に数字の7が表示され，どうやら6キー分ずれているようです。
![image](https://user-images.githubusercontent.com/6476040/132951523-e0d5e561-340f-4807-8437-3e9be0e847f8.png)

上記状態になった手順

せきごんさんのリポジトリ（https://gist.github.com/sekigon-gonnoc/57fbedc9a29e2c202b2aa52562fc0366 ）からuf2とJSONをいただいてそのまま使っています。
手順としては、ボタンを押したままPCに接続→ボタンを離す（ブートローダー状態）→uf2ファイルをドラッグ＆ドロップでファームウェア反映→Remapに接続→JSONを反映→自分の好みに合わせてレイアウトを修正→Flashで書き込み（ここまで一気に9/9夜）→今日(9/11)Remapに接続→報告した事象発生　です。

せきごんさんによる追試

- VIA とRemapに同時に接続したがRemapのほうだけずれが発生
- ローカルでremapを起動してcool836aを通さずにjsonをインポートしたら普通に表示された

せきごんさんによる可能性の推測

jsonをimportしてキーボードを切り替えたときに、前のキーボード向けに吸い出したキーマップのデータをそのまま使用してるから起きてるっぽいです。
- 最初に接続するとほかのキーボードの定義で表示される
- jsonをインポートするとレイヤ1以降がずれる
- レイヤ0を適当に書きかえてflash (remap側でキーマップの吸出しが再度実行される
- レイヤ1以降が正常に表示されるようになる

**Comment by yoichiro** [comment]
The pull request #613 causes other issue, therefore I reverted it.
