### ISSUE TITLE
It shows nothing when layout option is used.

### ISSUE THREAD

**Issue by 3araht** [remap-keys/remap#606]
https://user-images.githubusercontent.com/69518343/132968021-0c401818-4b7e-4ace-bf2e-1d2fa75c2a7f.mov

[ct_macropad_12only_json.txt](https://github.com/remap-keys/remap/files/7148856/ct_macropad_12only_json.txt)
[ct_macropad_both_json.txt](https://github.com/remap-keys/remap/files/7148857/ct_macropad_both_json.txt)

QMK Firmware 0.13.25
ct_macropad is used.
A month ago, it was working fine. However, the symptom shown in the video happened.
I tested with both Win and Mac. It was the same.
"ct_macropad_12only_json.txt" is a test file I made to see if it works. It does.
"ct_macropad_both_json.txt" is the problematic one.
![Screen Shot 2021-09-12 at 10 05 45](https://user-images.githubusercontent.com/69518343/132968071-8397fc33-b822-4315-8c37-b682f69e2e5f.png)

**Comment by yoichiro** [comment]
@adamrocker Could you check this issue?
