### ISSUE TITLE
Multiple keys are selected when changing a layout option

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#612]
After changing the layout option of the Attack25 keyboard, multiple keys are selected.

![E_C4T-XVUAANggP](https://user-images.githubusercontent.com/261787/133015097-ab3e0978-ce67-4172-88e4-f12a49897e19.jpeg)

Source: https://twitter.com/checkLa1n/status/1436851102004101123

**Comment by adamrocker** [comment]
I found some issues with the keyboard definition file(.json).
There are 2 same matrix index;'1,3' and '3,4', whenthose options are activated.
Is it possible to fix those matrix indexes as below?
<img width="428" alt="スクリーンショット_2021-09-13_17_09_43" src="https://user-images.githubusercontent.com/316463/133067238-e9fa51f5-1885-4f42-bb55-3c6d0a9b1db2.png">

**Comment by yoichiro** [comment]
@adamrocker Thank you for the investigating!

@monksoffunk We found some issues in the keyboard definition JSON file of your Attack25 keyboard. Could you confirm them and fix it? It would be happy if you update the JSON file into Remap after fixing it.

**Comment by monksoffunk** [comment]
Thank you for reporting the bug.
Already updated and I think working correctly now.

**Comment by yoichiro** [comment]
@adamrocker @monksoffunk Thanks. I close this issue.
