### ISSUE TITLE
Missing Magic Keycodes

### ISSUE THREAD

**Issue by jpskenn** [remap-keys/remap#636]
Some [Magic Keycodes](https://docs.qmk.fm/#/keycodes_magic) are missing.

- LCG_SWP
- LCG_NRM
- RCG_SWP
- RCG_NRM
- EH_LEFT
- EH_RGHT

**Comment by yoichiro** [comment]
@jpskenn These key codes have been added into the device category. Could you confirm them? Thank you for the feedback!

![Screenshot_20210917_152951](https://user-images.githubusercontent.com/261787/133735419-3fccfa46-2716-468e-b1d3-29dd70797e13.png)

**Comment by jpskenn** [comment]
Thanks to add key codes.
All key codes recognized as normal👍

I checked with this code.

```c
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
...
...
        case VERSION: // Output firmware info.
        case EH_LEFT:
        case EH_RGHT:
        case LCG_SWP:
        case LCG_NRM:
        case RCG_SWP:
        case RCG_NRM:
        case CG_NORM:
        case CG_TOGG:
        case CG_SWAP:
            if (record->event.pressed) {
                SEND_STRING (QMK_KEYBOARD ":" QMK_KEYMAP " @ " QMK_VERSION " | " QMK_BUILDDATE);
            }
            return false;
        default:
            break;
    }
    return true;
```
