### ISSUE TITLE
Please add LCG_SWP and LCG_NRM to REMAP.

### ISSUE THREAD

**Issue by jun3010me** [remap-keys/remap#641]
Please add the following two key codes to REMAP.
LCG_SWP
0x5cfb

LCG_NRM
0x5cfd

This is the key code to replace the Ctrl key and the ⌘ key.

For example, when copying and pasting on Windows, Ctrl + c and Ctrl + v are used, but on Mac, use ⌘ instead of Ctrl.

By switching between these two, you can realize a keyboard that can be used on both Windows and Mac.

Please do me a favor.

**Comment by jpskenn** [comment]
Please see #636.
Those key codes exist now, on DEVICE tab. (Build: 147)👍

**Comment by adamrocker** [comment]
I guess we can close this issue solved by another issue.
