### ISSUE TITLE
[Feature Request] SS_DELAY support for Macros

### ISSUE THREAD

**Issue by darakuneko** [remap-keys/remap#648]
It would be wonderful if it is possible to SS_DELAY.
https://docs.qmk.fm/#/feature_macros?id=tap-down-and-up

**Comment by yoichiro** [comment]
@darakuneko The macro feature provided by VIA doesn't support the `SS_DELAY`. https://github.com/qmk/qmk_firmware/blob/a116b3f1ae4e6dbd09c450bfc74dd2a64f66b7b1/quantum/dynamic_keymap.c#L195-L250
