### ISSUE TITLE
Can't update a key with DnD

### ISSUE THREAD

**Issue by yoichiro** [remap-keys/remap#692]
Currently we can't update a key with DnD as the following movie:

https://user-images.githubusercontent.com/261787/149048339-42823442-3559-4010-91e4-266838d47f37.mp4

**Comment by yoichiro** [comment]
@adamrocker Could you confirm and fix this issue?

**Comment by adamrocker** [comment]
@yoichiro I'm gonna check it :)

**Comment by yoichiro** [comment]
@adamrocker Thank you for the confirmation! It seems that this issue occurs on Linux Chrome only. I investigate this issue.

**Comment by adamrocker** [comment]
@yoichiro Thank you so much. It works fine with macOS's Chrome as I reported.

**Comment by yoichiro** [comment]
I tested this issue on Windows 11 and Chrome OS, but I was not able to reproduce this issue.

**Comment by yoichiro** [comment]
I close this issue because this issue might be occur on my Linux environment only.
