### ISSUE TITLE
[Feature Request] cheat sheet without blank layers

### ISSUE THREAD

**Issue by tom-tan** [remap-keys/remap#697]
We can get a cheat sheet of our keymap with `Get keymap cheat sheet (PDF)` button.
Currently it prints all 32 layers even if most of them are blank layers (i.e., layers in which all keys are assigned to `NOOP`).

It would be nice if we can get a cheat sheet without blank layers.

**Comment by yoichiro** [comment]
@tom-tan Thank you for the feedback.
