### ISSUE TITLE
[Feature Request]  Add support for extended keycode of BLE Micro Pro

### ISSUE THREAD

**Issue by sekigon-gonnoc** [remap-keys/remap#700]
BLE Micro Pro has feature called "[extended keycode](https://sekigon-gonnoc.github.io/BLE-Micro-Pro/#/edit_keymap_file?id=%e6%8b%a1%e5%bc%b5%e3%82%ad%e3%83%bc%e3%82%b3%e3%83%bc%e3%83%89)" which can realize some convenient functions without compiling firmware (e.g. Layer-Tap-Extended can set key with modifier to tap-code of Layer-Tap).

I'm planning to enable editing this extended keycode setting through Raw HID in next release of firmware.
My suggestion is to add support for this feature.

Implementation may be similar to macro support. An extended keycode configuration consists of 6bytes per key, and be saved separately with keymap. Keycode in keymap indicates the index of the extended keycode.
So what we need is new editor for extended keymap and getting/setting configuration through WebHID.

This is a screenshot of prototype version. If you are interested in this, I will submit a pull request.

![image](https://user-images.githubusercontent.com/43873124/158041812-1fb3e572-578b-48d6-b297-41b4900b481f.png)

**Comment by yoichiro** [comment]
@sekigon-gonnoc It seems that looks good to me. I look forward to checking a pull request for this.
