### ISSUE TITLE
Add User keycodes

### ISSUE THREAD

**Issue by knoopx** [remap-keys/remap#707]
Add user keycodes, as defined by VIA:
```
enum user_keycodes {
    USER00 = 0x5F80,
    USER01,
    USER02,
    USER03,
    USER04,
    USER05,
    USER06,
    USER07,
    USER08,
    USER09,
    USER10,
    USER11,
    USER12,
    USER13,
    USER14,
    USER15,
};
```

**Comment by mrnoisytiger** [comment]
It would be great to allow more than 16 user-defined keycodes. I have opened a PR on VIA to mimic the same: https://github.com/the-via/app/pull/44

It appears to be purely a UI issue. VIA recognizes the USER17-USER** keycodes in the UI but it is grayed out and not selectable.

![Screen Shot 2022-08-28 at 9 39 08 PM](https://user-images.githubusercontent.com/12619586/187124283-f199ab01-bd8e-4533-ba61-20b287e7c945.jpg)
