### ISSUE TITLE
Empty user name

### ISSUE THREAD

**Issue by otahinosame** [remap-keys/remap#713]
My user name is not displayed on the screen for saving and sharing keymaps.
When I Save and Share, my user name shows null.

![4A2B27E3-7782-4193-8490-91147B903341](https://user-images.githubusercontent.com/76490174/172526408-aa1bfc91-62a0-43b3-ac4a-2d051f5399d5.png)

![FD9FDDF2-40A7-4CB4-AD83-06C1CEA4E13F](https://user-images.githubusercontent.com/76490174/172526412-5c8e49c2-e793-44be-bd18-405cb40528ee.png)

**Comment by yoichiro** [comment]
@otahinosame I have fixed this issue by changing the logic like the following:

1. If `user.displayName` is not null, use it.
2. If `user.providerData[n].displayName` is not null, use it.
3. If `user.email` is not null, use its user name part.
4. Otherwise, use "(no name)".

**Comment by otahinosame** [comment]
@yoichiro Thank you. I tried sharing a keymap and it worked well.

**Comment by yoichiro** [comment]
@otahinosame Great! Thank you for the feedback.
