### ISSUE TITLE
Pressing Back on Keyboard Catalogue makes organizations disappear.

### ISSUE THREAD

**Issue by mrnoisytiger** [remap-keys/remap#717]
Pressing Back after entering a keyboard will make the Organizations filter fail to populate.

Steps to reproduce:

1. Enter Keyboard Catalogue
2. Click on Organizations filter and notice that 4 organizations are listed
3. Click into any keyboard listed on the Keyboard Catalogue
4. Press the Back button on the top-left corner of the Remap interface
5. Click on the Organizations filter again and notice that all organizations are gone.

![Screen Shot 2022-07-04 at 10 57 15 PM](https://user-images.githubusercontent.com/12619586/177259308-e1db3e44-5604-4cff-a3ea-e0ccc4907c37.png)

Note that all other filters populate without issue. No errors logged in console upon hitting back button.

**Comment by yoichiro** [comment]
@mrnoisytiger Thank you for this feedback. I intend to confirm this issue.
