### ISSUE TITLE
Layer 1 is not displayed.

### ISSUE THREAD

**Issue by telzo2000** [remap-keys/remap#718]
At cool650half, layer 1 is not displayed and layer 2 is displayed on layer 1.
Even if I change the key of layer 1 and overwrite it, it is not written.
When the key of layer 2 is changed, the behavior of replacing the key of layer 1 is shown.
I checked the firmware, but I couldn't identify the cause, so I wondered if there was something wrong with the remap side.
thank you.
https://github.com/telzo2000/cool650/tree/main/firmware_cool650_half

<img width="1011" alt="スクリーンショット 2022-07-13 20 04 19" src="https://user-images.githubusercontent.com/67196597/178720575-e199cc85-b7fd-425a-9f7d-8674f707c83d.png">
<img width="700" alt="スクリーンショット 2022-07-13 20 04 55" src="https://user-images.githubusercontent.com/67196597/178720620-55c01c88-8d1d-4ae2-bf13-7567ccd7da5b.png">

**Comment by yoichiro** [comment]
@telzo2000 Could you confirm whether there is an error message or not in the Console tab in the Chrome DevTools when your situation occurs?

**Comment by telzo2000** [comment]
Thank you for reply.
I looked at the Console tab in the Chrome DevTools and realized I was the culprit.
The cause was found to be a description mistake in info.json.
I updated the info.json and the issue was resolved.
Thank you for always helping me.

**Comment by yoichiro** [comment]
@telzo2000 Thank you for the confirmation. OK, I close this issue.
