### ISSUE TITLE
Claw44 `rev2` can't apply shared keymaps

### ISSUE THREAD

**Issue by gshmu** [remap-keys/remap#737]
my claw44 no shared keymaps
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1797676/192127956-216e155f-2845-4513-b622-eba77fb12302.png">

the shared keymaps list
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1797676/192128067-c7430023-f47b-486f-83bb-c711e1695b76.png">

please help

**Comment by yoichiro** [comment]
claw44 rev2 is not the same as Claw44.

<img width="718" alt="スクリーンショット 2022-10-19 20 28 24" src="https://user-images.githubusercontent.com/261787/196678641-8687c590-36ec-43e2-8571-c377849e9078.png">

**Comment by gshmu** [comment]
claw44 rev2 is based claw44, (add some new keys), I want apply claw keymap to rev2.

**Comment by yoichiro** [comment]
I know that, but the VID and PID of the claw44 rev 2 is different from them of claw44. Therefore, they are different keyboard in Remap.

**Comment by gshmu** [comment]
@yfuku can update the VIP and PID?

**Comment by yfuku** [comment]
@gshmu 
Thank you for using Claw44.
Claw44 rev1 and rev2 have different wiring, so they cannot share the same keymap.
We apologize for the inconvenience, but we would like to ask you to start from the beginning.
