### ISSUE TITLE
Extra key appearing when more than 1 layout in a json file

### ISSUE THREAD

**Issue by tinkerBOY-git** [remap-keys/remap#748]
I have this json file with two layouts in it but on 2nd layout there's this extra key appearing. It does not appear if there's only one layout in the json file.

see screenthot at https://ibb.co/2cHfYMH

**Comment by yoichiro** [comment]
We can't investigate your issue because of lack of information.

**Comment by tinkerBOY-git** [comment]
> We can't investigate your issue because of lack of information.

I pasted the json file at https://pastebin.com/CeB54x9V

**Comment by tinkerBOY-git** [comment]
I found the issue! Looks like some duplicate keys.
