### ISSUE TITLE
Keyboard registration should not require PRODUCT in config.h.

### ISSUE THREAD

**Issue by takai** [remap-keys/remap#754]
When registering a keyboard to Remap, the registration was rejected because "the product name does not match the actual PRODUCT value in the config.h file".

But QMK has recently moved their configuration to info.json; PRODUCT is no longer defined in config.h.

Please see below for details on the QMK changes:
https://github.com/qmk/qmk_firmware/blob/master/docs/data_driven_config.md

**Comment by yoichiro** [comment]
@takai We know that currently the PRODUCT is written in the info.json file. When we reviewed your applications, the product names you filled in to the application form were not matched to the keyboard_name values in the info.json files, therefore we rejected your applications.
