### ISSUE TITLE
LM code in menu list but not below in LAYER section

### ISSUE THREAD

**Issue by mxmilkiib** [remap-keys/remap#801]
I almost thought it was not available to bind!

**Comment by yoichiro** [comment]
@mxmilkiib Could you describe your suggestion more detail?

**Comment by mxmilkiib** [comment]
![image](https://github.com/remap-keys/remap/assets/108225/e1598ddd-bd77-40e1-95b3-d72106ebdef2)
![image](https://github.com/remap-keys/remap/assets/108225/148668c7-79a9-4504-9bfd-e1fcf37ff2d6)
LM is missing from first.
