### ISSUE TITLE
Radio button to make the kb layout be "part of the header"?

### ISSUE THREAD

**Issue by mxmilkiib** [remap-keys/remap#802]
Especially on zoomed in and non 4k screens, scrolling down to see the key codes available makes the layout become hidden. A radio button n I guess a tiny bit of JS n CSS to make the layout section "sticky" would make the layout accessible for dragging keys to it.

**Comment by mxmilkiib** [comment]
Huh, it is part of the header.. I got into a state where it somehow wasn't.. not sure how to reproduce..

**Comment by yoichiro** [comment]
@mxmilkiib Hmm, could you post the screenshot you face this issue?

**Comment by yoichiro** [comment]
I close this issue because of nothing more information.
