### ISSUE TITLE
Cannot restore the saved keymap

### ISSUE THREAD

**Issue by yukiyohure** [remap-keys/remap#851]
Once I saved the keymap by clicking the SAVE CURRENT KEYMAP, I could not restore the keymap I just saved.

https://github.com/user-attachments/assets/ef06a1fb-f0b7-403d-ad3a-a16a1554ba67

**Comment by yoichiro** [comment]
The behavior is as specification. The keymap which is already flashed is stored into the database.

**Comment by alexzaitsev** [comment]
I have the same issue. This behaviour doesn't look as expected for regular (especially new!) user.
